on: [push]

jobs:
  run_moban:
    runs-on: ubuntu-latest
    name: synchronize templates via moban
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: check changes
      run: |
        pip install "setuptools<80"
        pip install "MarkupSafe<2.1" moban gitfs2 pypifs moban-jinja2-github moban-ansible ruamel.yaml
        moban
        git status
        git diff --exit-code
    - name: Auto-commit
      if: failure()
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: This is an auto-commit
